### ISSUE TITLE
Book page displays Overdrive counts at random (?) library

### ISSUE THREAD

**Issue by auspex** [rhollister/goodreads#1]
I'm using the extension to track availability at the Halifax (NS, Canada) public library: http://halifax.lib.overdrive.com/, and so far it's always worked perfectly from "My Books".

Today I was looking at the page https://www.goodreads.com/book/show/23153154-memory-man and noticed it had Overdrive availability. But when I clicked on the overdrive link, I got the Seattle library! Where I certainly don't have an account.

Checking back in "My Books", it seems everything is using the Seattle link, and when I look at the extension Options, it's now set to `Using subdomain(s): spl.lib.overdrive.com`. The only way to set it back was to change my Overdrive URL and then change it back to the original.

**Comment by rhollister** [comment]
That's my fault, I added an update to support multiple libraries and changed the variable name. 

What must have happened is when Chrome automatically updated the extension, your saved library was saved in an old variable, and the new variable defaulted to Seattle. 

It shouldn't happen again. If it does, definitely let me know and I'll look into it!

**Comment by auspex** [comment]
Looks good to me.
