### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by aschnebe** [rhollister/goodreads#10]
I'm having trouble adding one of my libraries. It won't let me add it from the map, and when I add it manually, I get this error, even though the URL does contain overdrive.com: Error: OverDrive URL must contain .overdrive.com.

This is the library's URL: https://clc.overdrive.com/clc-columbus/content/
I've tried that, as well as just https://clc.overdrive.com

LOVE this extension btw.

**Comment by edglazer** [comment]
I have a similar problem, trying to set it up. Automatic detection using the map didn't work, so I went to the manual setup. For me the library URL is:
https://mlc.overdrive.com/mlc-capitalarea/content

and I try entering variations:
https://mlc.overdrive.com
http://mlc.overdrive.com
mlc.overdrive.com

This is Chrome version  54.0.2840.98 (64-bit) on macOS 10.11.6 if it helps?
Such a good plugin idea, you are the best!
