### ISSUE TITLE
Not loading available books

### ISSUE THREAD

**Issue by ShannaRedwind** [rhollister/goodreads#12]
Hi, I love this extension and use it daily.  Thank you so much for creating it.

Just today the available books stopped loading up.  With my very limited tech skills I went through the process of closing the browser, restarting the computer, deleting and re-installing the extension.  Then I tried adding random libraries discovered that other libraries did load, but not mine.

I already miss using this.  I hope there's something I can do. Here's the little bit of information I managed to acquire:

This is the library information that comes up on the setup
Ontario Library Service Consortium
odmc.lib.overdrive.com

I tried your other methods to see if the address had changed, but couldn't find any useful information.
I a search for odmc.lib.overdrive.com on the source and it didn't find it.

There was 600+ results for .overdrive.com
One that appeared many times didn't work: libraryreserve.cdn.overdrive.com

And the DNS lookup came back with this ontario.libraryreserve.com.

**Comment by rhollister** [comment]
For privacy reasons, I had limited the sites the extension was allowed to contact. Some Overdrive sites started using libraryreserve.com which wasn't in the allowed list. 

This should now be fixed in version 3.3.0!
