### ISSUE TITLE
AG extension started reporting "not found" on every book, every library; starting yesterday

### ISSUE THREAD

**Issue by whozits** [rhollister/goodreads#14]
Users are reporting the same thing on the AG chrome extension site's Support tab.

**Comment by erinco25** [comment]
I'm seeing the same issue.

**Comment by tarapeltier** [comment]
In case it helps, I found this in the console: 
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'length' of undefined
    at chrome-extension://gclnfffacbjpclfenjgefpfnafmjghhk/src/goodreads_inject.js:307:42

Here's lines 307-311:
	if (onlyRecommendations && **message.books.length** > 0) {
		sortScore = 9998;
		listingStr = "<font color=#C60>request<hr width=10px class=AGline><span class='AGtitle'>Recommend " + message.libraryShortName + " add this to their collection</span></font>"
	}

**Comment by rhollister** [comment]
Thanks! It looks like Overdrive stopped including the attribute for available copies on their search results page.  Should have an easy update out shortly!

**Comment by tarapeltier** [comment]
Thanks rhollister - I can't tell you how much I LOVE this extension.

**Comment by dneighbors** [comment]
Love this extension.  Happy to hear and update is coming!  I about panicked when was getting no results. :)

**Comment by rhollister** [comment]
I've just released a new version 3.4.0 that should work. Let me know if you have any issues!

**Comment by crackthesafe** [comment]
Hi! The new version now sees if a book is owned by a particular Overdrive site, but it's not catching the availability correctly or the number of copies. (And THANK YOU for this extension! I absolutely love it.)

**Comment by rhollister** [comment]
My bad! I verified it with a number of library sites, but very likely I missed something. Which library and book are you seeing a discrepancy with?

**Comment by crackthesafe** [comment]
I'm just cherrypicking stuff here, but Windwitch by Susan Dennard at the Brooklyn Public Library (https://brooklyn.overdrive.com/) is showing in Goodreads as 8/5 holds but BPL owns 4 copies. "Be the boss everyone wants to work for" is showing as 0/3 holds in GR but is available at BPL. "Library at Mount Char" by Scott Hawkins shows 0/1 holds but is available at the Houston Area Digital Media Catalog (https://hadc.overdrive.com/). Basically all items are showing as checked out at all my libraries (I have 3 added right now), even if they're available; and if they ARE checked out then the holds/available copies is incorrect. I hope that helps!

**Comment by rhollister** [comment]
Not cherrypicking at all, this is perfect. I'll try to get a fix out tonight for it.

**Comment by rhollister** [comment]
Great catch @crackthesafe. I was missing a pipe so that every book had +1 holds. Just published 3.4.1 which fixes it.
