### ISSUE TITLE
"not found" - have you looked at Overdrive's APIs?

### ISSUE THREAD

**Issue by troypesola** [rhollister/goodreads#15]
Overdrive has published APIs for libraries, search, and availability.

I don't know if you've tried to apply for API access, nor how that would be handled with an opensource project.  Looks like they review projects then they grant secret key credentials for the project/application required for using the api.

But assuming you could get API approval, the APIs might be easier to use than using jQuery to parse the DOM from resulting pages.  The availability API returns JSON results.

Glad to help, if that's an approach you're interested in.

I tried to look at the dom structure of the current UI and I don't see an easy way to pull the results.

   -Troy

Here are a few links to Overdrive's APIs:

https://developer.overdrive.com/
https://developer.overdrive.com/apis/library-availability
https://developer.overdrive.com/apis/search

**Comment by rhollister** [comment]
Yes! I've looked at their API and would love to use it. The problem is that I would have to include the secret key in the extension- which wouldn't be so secret then. 

I could still do so by sending all requests through my own server which then adds the secret key and passes them to Overdrive. I'd be happy to do so, but permanent hosting (not just running a box from home) of course costs money, and there's no easy way to really monetize this extension (no place for ads, Amazon affiliate links, and certainly not going to charge money).

I've made requests (officially and unofficially to contacts there) to Overdrive asking if the read and searching APIs could be open, but never heard anything back. 

It would absolutely be the preferred way of doing so.

**Comment by troypesola** [comment]
Exactly my conclusion as well.

I love your extension, but at the same time I don't see the value in setting up and using your own server to jump through to hide those keys.

Would be nice if Overdrive could provide a set of API keys for a sub-set of the APIs for public consumption and use.  I've sent a support request into them as well.

I suppose in the meantime it may be possible to access the script values embedded in window.OverDrive.mediaItems.   It looks like the JSON that is returned from the availability API call.    I tested it out by pulling the search URL from your extension, loading it in a different tab and inspecting the page.  The script object has attributes like isAvailable, ownedCopies, availableCopies, holdsCount.

I'd have to play with it, but seems like we'd be able to just access that object and skip parsing the dom to find the info.    Just a thought.

  -Troy

**Comment by erinco25** [comment]
I would be willing to donate toward hosting for this extension! I bet others would be too.

**Comment by troypesola** [comment]
Okay so I pulled down the code and hacked in an approach that checks for the window.OverDrive.mediaItems block and if it is found then it parses the JSON and uses the results.

Here is the background.js file with my updates.

[background.txt](https://github.com/rhollister/goodreads/files/863180/background.txt)

I'm using this with my local and it appears to be working.  I will continue to test.

  -Troy

**Comment by rhollister** [comment]
This looks great Troy. Finding `window.OverDrive.mediaItems` was brilliant. I'm close to pushing out an update soon!

**Comment by rhollister** [comment]
I've just released a new version 3.4.0 that should work. Let me know if you have any issues!

**Comment by troypesola** [comment]
I updated to your version and it is working for me.

Glad to help out.  I was able to fill up my Kindle again.  phew.

**Comment by rhollister** [comment]
Speaking of Kindles, I'm about to push up a script you might be interested in. It automatically "buys" free Kindle books from Amazon's free daily deals that get good reviews on Goodreads. 

It will then email you a digest of purchases and skipped purchases based on keywords or categories (eg "paranormal romance fan fiction").
