### ISSUE TITLE
No books showing available

### ISSUE THREAD

**Issue by ShannaRedwind** [rhollister/goodreads#16]
Hi,  Maybe this is just a huge run on books at my library, but there are no books showing as available on my available goodreads to read list of over 500 books.  There are also none available on the 2 lists that I've looked at.

I checked, and some of the books that are labeled 0/1 or 0/3 or anything like that are actually available when I clicked the link and went to the site.  It's still showing multiple holds

Thanks for creating this wonderful extension.  I use in constantly.

**Comment by rhollister** [comment]
Hey, I think I may have fixed this in 3.4.3. Let me know if you're still seeing this same problem!

**Comment by ShannaRedwind** [comment]
I'm afraid I'm still having the same problem.  There are no books showing as available, so some of the 0/1, 0/2 etc. books are actually available and some are not.  It's still usable like this, just a couple of extra clicks to see if something is actually in.

I've checked a few others and everything with someone on a hold list seems to have an accurate number as far as I checked.  It's just the available books that seem to have a problem.

Thanks so much for looking into this

**Comment by rhollister** [comment]
There's definitely a possibility this could happen if Overdrive does things differently. Which book and library are you seeing this for?

**Comment by ShannaRedwind** [comment]
The library is Ontario Library Service Consortium.  It's doing it for all available books, but here are a few examples  Secret Gardens by David Belbin, Flash Fire by Caroline B. Cooney, Beyond the Door by 	
 Maureen Doyle McQuerry.

**Comment by tarapeltier** [comment]
THANKS for the 3.4.3 update.  I'm seeing similar behavior for books that are available with both libraries I can access.

Example:  A Little Life by Hana Yagahira  (https://www.goodreads.com/book/show/22822858-a-little-life)  Hennepin County Library shows 36 available copies but in reality - they have 1 available copy of 36 total copies (http://hclib.overdrive.com/search?query=A%20Little%20Life%20Hanya%20Yanagihara)

**Comment by ShannaRedwind** [comment]
Thank you for whatever you did.  I'm now linked to the new look for the site and everything seems  to be showing up properly as available on Goodreads.

**Comment by ShannaRedwind** [comment]
Not as big of a deal, but now none of the books that are not in the system, but that you can request are showing up.  But honestly I'm not terribly concerned about that, personally.
Actually, strangely I came across one that says request, but there's pages of them that I moved into a folder 'request overdrive' that no longer show up as request, but as 'not found'
