### ISSUE TITLE
Availability reporting inaccurate

### ISSUE THREAD

**Issue by smschwartz** [rhollister/goodreads#17]
Availability is not being reported accurately. Although some books marked as available are, in fact available, many others are reported as available when they actually have holds on them.

I'm not sure how many libraries you have available for testing, but an example is "Language of Sisters" by Amy Hatvany. It shows 1 available, but in fact there's 0/1 copies available. This is at Carnegie Library of Pittsburgh. I can dig in further into the js, etc. tomorrow if you need an example.

**Comment by troypesola** [comment]
I had the same problem.  I switched back to my local version with the "hack" that I submitted to fix this issue before and this version is reporting correctly.   I haven't had time to look directly at the code in the the repo, but something is different.   I'm heading into some travel, so not sure if/when I'll have time to take a look.

**Comment by rhollister** [comment]
Sorry about, it was a simple error on my part. This should be resolved now in 3.4.3!

**Comment by smschwartz** [comment]
Terrific!  Checked a few books that weren't correct before and all seems to be well. Thanks for the fix.
