### ISSUE TITLE
King County Library System (KCLS) Dodging AG?

### ISSUE THREAD

**Issue by d19jordan57** [rhollister/goodreads#18]
Until a month or two ago AG worked fine with the King County Library system (KCLS) but then they changed their URL (https://kingcounty.libraryreserve.com/10/50/en/Default.htm ).  There no longer appears to be an Overdrive-related URL, or it's well hidden.  I've tried the various suggestions in the AG app's configuration screen to no avail.  AG is such a good app and KCLS such a good (and large) library that I hate to lose access via AG.  Have you any other suggestions I might try for uncovering the URL that will enable KCLS to work with AG again?
Thanks.
DJ

**Comment by wlockwood** [comment]
A year late as I only just now saw this, but I use kcls.overdrive.com as my Overdrive URL and it's worked since late 2016, I think.

**Comment by rhollister** [comment]
Let me know if you're still having this issue with 5.0.1
