### ISSUE TITLE
Too many books reported as available.

### ISSUE THREAD

**Issue by taylorkline** [rhollister/goodreads#19]
Not a critical bug at all, but I noticed that even if a book has even one copy available, it may report `${TOTAL_COPIES} available`.

For example, [The Name of the Wind](https://lapl.overdrive.com/media/204579) on Overdrive has 1 of 36 copies available, but this extension injects a message that [36 copies are available](https://imgur.com/a/UOn3X).

**Comment by rhollister** [comment]
I just updated the design entirely for 5.0.0 since implementing the "estimatedWait" field in the API. Results should be more accurate, and links also default to Libby. Also added imports/export of settings.
