### ISSUE TITLE
Availability column not appearing on bookshelves

### ISSUE THREAD

**Issue by linmalex** [rhollister/goodreads#23]
I have just installed this extension today and added two libraries. It seems to be working fine for both libraries on the Book Description page, but I have been unable to get the column added on the bookshelf for availability. Is there a setting I need to fiddle with?

**Comment by ShannaRedwind** [comment]
Yes, that column seems to have vanished.  I've been using it, though possibly not in the past little while, so I'm not sure exactly when it vanished.  This is such a great extension, and that column was probably the part of it that I used most.

Thanks so much for the time you put into this.

**Comment by damonbauer** [comment]
This is fixed in #24, waiting for that to be merged.

**Comment by rhollister** [comment]
Looks like Goodreads updated their bookshelf page. The extension should now be working in 3.4.4. Thanks @damonbauer for the fix!
