### ISSUE TITLE
State of the firefox addon

### ISSUE THREAD

**Issue by bitboxer** [rhollister/goodreads#26]
Just a short question: i am a firefox user and am curious about the state of the firefox version. I see that there is a directory here for firefox, but don't see it in the firefox app store. Is this already working or does it need some polish? I would love to help you with finishing this. Maybe we can build it in a way that both use the same code. Firefox uses the chrome web api with a couple of minor tweaks that can be abstracted with a proper build pipeline.

**Comment by gartkb** [comment]
I love this addon so much, and I would love even more for there to be a firefox version. Please!!

**Comment by rhollister** [comment]
It's now available! https://addons.mozilla.org/en-US/firefox/addon/available-reads/

**Comment by bitboxer** [comment]
Hooray! This is awesome. Thanks for this.

![A whole rack of books in a library is moved using a special device on wheels.](https://media.giphy.com/media/YGlRW1Am9q7e0/giphy.gif)

**Comment by rhollister** [comment]
Y'all might be interested to know as of 3.6.0, the Firefox version also supports Firefox Mobile. This is probably the biggest feature I've wanted in a looong time. Now I don't have to worry about finding new books before leaving on a trip- I can just do it on the go!

I also noticed Goodreads has started including more authors (introduction, translator, afterword, etc) which is throwing off the searching, so going to get that fixed before making a larger announcement.

**Comment by gavinr** [comment]
Thank you for this update!
