### ISSUE TITLE
Available Goodreads list column disappeared a few days ago

### ISSUE THREAD

**Issue by whozits** [rhollister/goodreads#27]
I just noticed my extension stopped working today, May 22.  It was working two weeks ago.  "Stopped working" means the Available Goodreads column disappeared from Goodreads webpages.

Two other people have reported the issue on the extension's Play Store site.

**Comment by wlockwood** [comment]
I saw this as well, but it's not actually that the extension stopped working entirely. If I look at a single book's page, it shows what is available, but Available Goodreads' _On Overdrive_ column has disappeared from my shelves views.

**Comment by rhollister** [comment]
Thanks @damonbauer for beating me to the fix. I've published a new version to the Chrome Store and should be auto-updated as 3.4.5.
