### ISSUE TITLE
all books saying "not found"

### ISSUE THREAD

**Issue by lexipmagnus** [rhollister/goodreads#29]
First off, thank you for this extension. It's made it so I could find books across several libraries and can always have something on hold- I listen to about 3 books a week and your extension has saved me so much time and energy. It's the best. 

it's just not working for me right now. I have four libraries connected and they all say that every book is "not found." I tried updating chrome and uninstalling and reinstalling the extension. That's the complete end of my technical know how, and this could totally be user error. 

The libraries I have are Kitsap Regional Library, Utah County Library. Salt Lake County Library and Broward County.

**Comment by edglazer** [comment]
I'm having this problem also. https://mlc-capitalarea.overdrive.com/ and https://woodlands-eastlansing.overdrive.com/

update: bizarro, I just signed in to both libraries and now it looks like it's working. Didn't realize I was signed out. Maybe double check that you're signed in to the library's overdrive page @lexipmagnus ??

**Comment by gartkb** [comment]
What I noticed about this was, for me, that when I was opening the library page they had a greeting page pushing libby on me.  So the addon wasn't getting the response it expected.  Once I clicked through, that popup page no longer happened, and everything was fine.  So if that's still happening to you, check that.

**Comment by rhollister** [comment]
Hey, sorry for the long long delay, but the extension is updated and working again! Let me know if you find any issues.
