### ISSUE TITLE
Reordering a shelf loses the "On overdrive" column

### ISSUE THREAD

**Issue by auspex** [rhollister/goodreads#3]
If I have an "ordered" shelf, 
![shelf](https://cloud.githubusercontent.com/assets/464571/8041868/b67ca762-0df1-11e5-8945-6ff06da4fa8a.png)
and I move a book on the shelf, 
![shelf1](https://cloud.githubusercontent.com/assets/464571/8041921/0746af8a-0df2-11e5-8e63-6af284e71d2c.png)
the `<tbody id="booksBody">` element gets refreshed (but not the `<thead>`), resulting in the Overdrive results being discarded but the heading being kept.

**Comment by rhollister** [comment]
Great catch, should be fixed.
