### ISSUE TITLE
Export and import libraries configuration

### ISSUE THREAD

**Issue by gartkb** [rhollister/goodreads#38]
I have enough entries in my libraries that when I get a new device, or switch between tablet and phone, or PC, phone, tablet it would make life quite a bit easier to be able to sync configurations through import and export of the config file.  I try to do this manually now, but it's hit and miss whether it works properly or not between platforms. This is a really useful plugin, thanks. [In case anybody wonders how I'm using this on mobile, I use Kiwi browser which supports chrome addons.]

**Comment by rhollister** [comment]
This is a great idea! I've often run into the same problem.

Also: secret pro-tip: it will also work with Firefox Mobile (I'm still beta-testing it, feel free to give feedback)

**Comment by zanymuzik** [comment]
I love this extension too. 
And similar to the bluenote73, I would love to have to some way to backup and re-use the library configuration (even dirty is fine for now).

**Comment by gartkb** [comment]
I got a new phone 😬

**Comment by zanymuzik** [comment]
@bluenote73 - can you share how you export and import the config?

**Comment by rhollister** [comment]
I just added imports/export and updated the design entirely for 5.0.0 since implementing the "estimatedWait" field in the API. Results should be more accurate, and links also default to Libby.
