### ISSUE TITLE
Extension doesn't work with the new Goodreads layout

### ISSUE THREAD

**Issue by driscoll42** [rhollister/goodreads#40]
Goodreads is beta testing a new layout for books on the site, and this extension does not work with it.

Beta:
![image](https://user-images.githubusercontent.com/4751505/140163133-7cf961ec-8b30-4b7e-aa80-0263422ee705.png)

Old:
![image](https://user-images.githubusercontent.com/4751505/140163171-0915fc90-31ff-49c6-81ba-440acd09404e.png)

**Comment by gradiian** [comment]
I created a fork which I'm updating to work with the newest Goodreads layout: https://github.com/gradiian/goodreads2

So far it's partially working but I'm not familiar with JS so it's going to take a bit. I submitted a first release of the extension for Firefox under the name "Available Reads 2".

**Comment by edmcman** [comment]
@gradiian Have you considered making a PR?  @rhollister Are you alive?

**Comment by rhollister** [comment]
Hey, sorry for the long long delay, but the extension is updated and working again! Let me know if you find any issues.
