### ISSUE TITLE
"Loading" never finishes

### ISSUE THREAD

**Issue by kmboyett** [rhollister/goodreads#42]
Love this app, but stopped working at some point this year - I've got it installed on both Firefox and Chrome and both just show "loading x library" but never managed to get anywhere.

I've tried reinstalling the add on, different computers/browsers, run all my updates, even looking at smaller lists thinking it may just be taking too long to load the whole thing, but no love.

Help?

**Comment by sammychien** [comment]
Have you tried checking the "Uses new OverDrive site" setting? 
![image](https://user-images.githubusercontent.com/32807210/149068737-210db37c-0307-44d2-9361-9f601425d27a.png)

Checking that option for my libraries seemed to solve the problem.

**Comment by kmboyett** [comment]
I hadn't noticed that before, but unfortunately it doesn't seem to help.

**Comment by sammychien** [comment]
Could you post the overdrive URLs that you're using? For example: austinlibrary.overdrive.com, houstonlibrary.overdrive.com, etc.

**Comment by kmboyett** [comment]
https://frisco.overdrive.com/
https://houstonlibrary.overdrive.com/

**Comment by kmboyett** [comment]
It's working! Not sure what changed, but it seems to be working!
