### ISSUE TITLE
Filtering to only eBooks OR audiobooks

### ISSUE THREAD

**Issue by lowellbander** [rhollister/goodreads#43]
Hi! First things first, this extension is astounding, thank you so much @rhollister and team for building this!

My partner is only interested in eBooks, and I'm only interested in audiobooks. Would y'all be able to pass me some code pointers for where I might add such a filter, perhaps to the set up view? Thank you!

**Comment by lowellbander** [comment]
oh hmm perhaps #22 does this?

**Comment by lowellbander** [comment]
I tried a workaround of cloning the repo and then manually loading the extension into Chrome, but am now running into the error that jQuery isn't defined. Perhaps I didn't run the build script properly?

![image](https://user-images.githubusercontent.com/3479724/151646424-dcc14764-fdb4-4708-b5e8-7a279a3dff7b.png)

**Comment by rhollister** [comment]
Hey, sorry for the long long delay, but the extension is updated and working again! Let me know if you find any issues.
