### ISSUE TITLE
Support for new Goodreads UI

### ISSUE THREAD

**Issue by rdoherty47** [rhollister/goodreads#44]
Goodreads has been testing the new UI on some customers, and I was one of them. I'd occasionally see the new UI as part of a beta program. AvailableReads never worked on this new UI, so I always asked to go back to the old UI. I see a note today that the beta has been discontinued and the new UI will be rolling out to all customers soon. Is there a plan to update AvailableReads to work with this new UI?

**Comment by elizrich** [comment]
The new book page is already being rolled out and I, unfortunately, have to use it. The new Goodreads book page no longer accommodates this wonderful extension. It still works on other areas of the site. I look forward to being able to see it on the new book page.

**Comment by elizanca** [comment]
Ditto. I just joined Github so I can follow updates on this browser extension. It's so useful! But I'd love not to have to add a book to my shelf before it will work.

**Comment by ljd144** [comment]
Also following for updates.  I'm glad the plugin still works on the shelf pages, but I'm sure goodreads will be updating those to the new UI also.

**Comment by crunkilton** [comment]
I'll chime in to say that I also love this extension and would appreciate if it could work with the new UI! I would offer to help but I don't know javascript, regrettably, so doubt I could add much here.

**Comment by gartkb** [comment]
This was a real gamechanger of an addon, I'm so sad I won't be able to use it for now

**Comment by Porges** [comment]
Since this extension isn't working on the new page any more, I made an extension for my own use. It might help some other people: https://github.com/Porges/find-reads/

Note that it _only_ works on the per-book page and not in the page lists like Available Reads does.

**Comment by elizrich** [comment]
Thank you, George! This works on the book page and I still have the other extension for My Books.

**Comment by Porges** [comment]
> Thank you, George! This works on the book page and I still have the other extension for My Books.

Good to hear that it works for someone other than me 😄

**Comment by rhollister** [comment]
Hey, sorry for the long long delay, but the extension is updated and working again! Let me know if you find any issues.

**Comment by elizrich** [comment]
Thank you. It stopped working on my shelves so I knew I need to do something on my end. I reset “Uses Old Overdrive Site” and it now works like a charm. 

 

Elizabeth

**Comment by elizrich** [comment]
There is an enhancement today (9/24/23) showing on my shelves. It expands on my shelves showing the title being searched. This now requires scrolling to see the right side of the data. This makes the extension undesirable. I see it also shows more information on the Book page. I hope you will consider reverting this enhancement.

**Comment by rhollister** [comment]
Ah, sorry about that. I bet it needs a max width setting. Can you tell if it's a specific title result that is making the column so wide? Could you share which book and library is giving that result?

**Comment by elizrich** [comment]
It is on all of my shelves. And yes, it is a longer title, but I’m not interested in it showing any of the searched for titles. The book shows on my shelves anyway. It used to show just “not found” or Number available or Number of holds. That was terrific.

 

Thank you for the quick response, by the way.

 

Elizabeth

 

This is a small shelf where the data is readable.

 



 

 

This is my Overdrive shelf where the data is not readable. The long title is Valiant Ambition: George Washington, Benedict Arnold, and the Fate of the American Revolution by Nathaniel Philbrick

**Comment by rhollister** [comment]
It doesn't look like pictures came through.

The reason for including pictures and titles was to help avoid always hovering through a list of results to verify the title+author matched. Are you wishing for a more compact view? I'd be happy to add more preferences allowing something like that.

After fixing the width issue so you don't have to scroll to the right, would you prefer:
Option A) In the current design, limit results to only the top 5 or so being shown and an option to "show more results"
Option B) Compact everything to one line (and thus also shrink book cover picture)
Option C) Go back to the previous design where you have to hover over to see the title+author

**Comment by crunkilton** [comment]
I for one prefer the older condensed view (I rarely had issues with the
wrong book being found, and being condensed makes it easier to search and
scan visually). Regardless of whatever you end up doing, thank you for
supporting this project!

sent by my phone

**Comment by elizrich** [comment]
I prefer:

C) the previous design. I have never hovered over the title/author. It always went to the correct title/author when I clicked on the results.

**Comment by elizrich** [comment]
I see now that the header on My Shelves says “on libby”. And on the book page it says “Availability on Libby.” This is another unwanted change. I don’t use Libby. I don’t have nor use a Libby app and never have. The search goes to my library consortium at overdrive.com

**Comment by elizrich** [comment]
I’m having a hard time with this now. It doesn’t take me to my library. It goes to Libby, which seems difficult to use and isn’t intuitive. I don’t want that and that isn’t what I’ve set this up for. I’m unlikely to use this extension with the recent changes

**Comment by crunkilton** [comment]
> I’m having a hard time with this now. It doesn’t take me to my library. It goes to Libby, which seems difficult to use and isn’t intuitive. I don’t want that and that isn’t what I’ve set this up for. I’m unlikely to use this extension with the recent changes

If it helps, Libby is an app that Overdrive created and they both point to your library. You can still access everything that your library has with it, it just has a different UI. I had to type in my library card number but after that it seemed to work well for me.

Either version of this extension works fine for me, the older version was working well for me but I can see how some of the new features would be useful to have and I'm sure I'd get used to it over time. Thanks @rhollister for keeping this updated, it's a great extension that has been a game changer for me, I appreciate the work you put in to maintain it!

**Comment by rhollister** [comment]
Thanks @crunkilton ! @elizrich there's a preference setting to switch back to Overdrive results specifically because I knew people would have that preference 🙂

Libby is clearly the way all Overdrive is going, so I made the decision to default to it. I personally still use Overdrive though.

I should have a new update 5.1.0 tomorrow that has more preferences for a more compact layout.

**Comment by elizrich** [comment]
I don’t understand what you mean by preference setting. When I click on the “2 Available” it takes me to the Libby URL , not to the Overdrive URL. When I say “my” library, it isn’t my local library. It is the state library and has only digital items. (adl.overdrive.com)

**Comment by rhollister** [comment]
Under the extension options for AvailableReads there are several extension-specific preferences.

The easiest way to get to it is to:
1. Go to goodreads.com
2. Click the puzzle-piece icon in the top right to bring up the Extensions menu
3. Next to AvailableReads click the 3 dots to open the submenu
4. Click Options
5. There's a Preferences section with several preferences

**Comment by elizrich** [comment]
Perfect! Thank you!

**Comment by elizrich** [comment]
How is the work going on getting a more compact layout? (And thank you again for the pointer to the Overdrive preference!)

 

Rhollister wrote: I should have a new update 5.1.0 tomorrow that has more preferences for a more compact layout.

**Comment by elizrich** [comment]
I didn’t notice before, but when the title and author search is displayed, the author name is given as last name first name, without a comma between names as is standard for this format. If the intention is to continue showing this information, then it would be preferable that the display be first name last name, or at the very least with a comma after the last name and before the first name.

 

I should have a new update 5.1.0 tomorrow that has more preferences for a more compact layout.

—

**Comment by rhollister** [comment]
Apologies for the delay, I added a lot more preferences just for you @elizrich 😊
Hopefully you can tweak it to just how you like it. I've submitted the update, look out for version 5.2.0 by tomorrow.

<img width="474" alt="image" src="https://github.com/rhollister/goodreads/assets/3998680/08bc29b8-f1f6-4fe3-8342-073e44eaec07">

**Comment by elizrich** [comment]
This looks fabulous! Thank you!

**Comment by elizrich** [comment]
The field is definitely more compact. I selected to not show title and author in results, and, when Overdrive has a copy, title/author does not display, but when the result is “not found” the title/author still displays.  I’m not sure what the “show more” is supposed to do. This is great progress, and thank you for working on this.

**Comment by rhollister** [comment]
Ah, that's a good point. I just published a fix for that in 5.2.1. 

"show more" will show you more results.

**Comment by elizrich** [comment]
The 5.2.1 fix showed up today. The title/author is gone and that is the good part. Unfortunately, it no longer shows availability either. No “not found”; no 1 Available;  no 2/1 Holds. Nothing. The column heading is on my shelves and Availability on Overdrive is on the book page, but there is no information provided in either place. I have tried selecting various options to see if one or the other made a difference, but without success.

**Comment by elizrich** [comment]
This looks absolutely perfect this morning! Thank you thank you thank you
