### ISSUE TITLE
Use Library Extension, this extension is broken and seems abandoned

### ISSUE THREAD

**Issue by gartkb** [rhollister/goodreads#45]
https://chrome.google.com/webstore/detail/library-extension/chkgcmmjoejpekoegkedcpifgfhpjmec?hl=en

**Comment by edmcman** [comment]
Library Extension is ok, but it doesn't work well in lists.  There is a beta option to turn it on in Goodreads lists, but you still have to manually click on each book to search.

**Comment by rhollister** [comment]
Hey, sorry for the long long delay, but the extension is updated and working again! Let me know if you find any issues.
