### ISSUE TITLE
Extention suddenly requires access to browsing history

### ISSUE THREAD

**Issue by Warr1611** [rhollister/goodreads#46]
Browser: Brave
[Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)](https://brave.com/latest/)

I had this extension installed, but today it disabled unless I grant permission to read my browsing history.

**Comment by rhollister** [comment]
Whoa, it shouldn't be doing that. I've restricted a lot of the permissions from the previous version actually, the only new one is "tabs" that might be triggering that.

I haven't tested it in Brave, let me play around with it.

**Comment by rhollister** [comment]
Whoops, yes, that was it. It doesn't need "tabs" permission to use chrome.tabs.
https://developer.chrome.com/docs/extensions/reference/tabs/

Publishing a fix now. You'll see it as version 4.2.1 probably by tomorrow evening. Latest is also pushed to master if you want to build it yourself.

**Comment by ilg** [comment]
FWIW, even after updating to 4.2.4, I had to remove the extension and re-add it to get Chrome (114.0.5735.133 on macOS) to stop telling me it wanted the browsing history permission.

**Comment by rhollister** [comment]
I just updated the design entirely for 5.0.0 since implementing the "estimatedWait" field in the API. Results should be more accurate, and links also default to Libby. Also added imports/export of settings.
