### ISSUE TITLE
4.1.0 NOP on Firefox 114.0, Linux

### ISSUE THREAD

**Issue by edsantiago** [rhollister/goodreads#47]
Thank you for resurrecting this extension! It does not seem to be working on my setup: Firefox 114.0, Gentoo Linux. I have wiped and restored (via Overdrive links) my list of libraries.

Symptom: 
* on book page, I see nothing new. In-page search for "verdr" yields no results. This is the new, de-improved book page.
* on to-read page, at page load time, I see the `rating` heading shift right, a new `on overdrive` column added (just like the old days). None of the actual data columns shift, though, so the content under `on overdrive` is empty stars. See attached image. Inspector shows an error in red:
```
SyntaxError: Document.querySelectorAll: 'tr.bookalike:not(:has(td.AGseen))' is not a valid selector
```
No smoking gun (to my eye) in the book page. Many requests blocked by Privacy Badger, uBlock Origin, and pi-hole... but symptoms are identical even with all of those disabled.

Thanks in advance for any help. I'll be glad to provide more details.

![gr](https://github.com/rhollister/goodreads/assets/265639/98377212-a890-4a6e-b1c0-8663cd5ab137)

**Comment by rhollister** [comment]
Look out for version 4.2.3 and let me know if you still have the same issue.

**Comment by edsantiago** [comment]
4.2.3 fixes the book page! `Availability on Overdrive` now appears after a second or two, with results as expected.

My Books, though, is unchanged. Exactly the same as the image above, with the same AGseen error. Shelf makes no difference.

In case it helps, there are two warnings and one error just before the syntax error:
>[warning] Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.
>[error] Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fls-na.amazon.com/..... (Reason: CORS request did not succeed). Status code: (null)
>[warning] Expected ‘none’, URL, or filter function but found ‘flipv’.  Error in parsing value for ‘filter’.  Declaration dropped.

(actually more warnings, but none seem related IMO)

I've reloaded with Ctrl-Shift-R. Have not restarted browser.
