### ISSUE TITLE
All library entries stuck at "Loading" on all pages.

### ISSUE THREAD

**Issue by bikram-agarwal** [rhollister/goodreads#48]
Chrome 116.0.5845.42 (Official Build) beta (64-bit)
Available Reads v4.2.4

On goodreads' "my books" list, or search result page or any individual book's page - the books' availability doesn't appear. The extension stays stuck at "Loading" indefinitely. 

![goodreads (2)](https://github.com/rhollister/goodreads/assets/4424058/badd6217-9353-4746-b7bd-122db377b001)
![goodreads (1)](https://github.com/rhollister/goodreads/assets/4424058/8014e0f8-48dd-4ad6-81c5-1f3a2df7ffc0)

I've cleared browser cache. Tried it in incognito etc. Issue persists.

**Comment by holyspiritomb** [comment]
You might have to check "Uses new Overdrive site"

**Comment by rhollister** [comment]
Let me know if you're still having this issue in 5.0.1.
