### ISSUE TITLE
Question on replicating in node.js

### ISSUE THREAD

**Issue by dave-linsalata** [rhollister/goodreads#7]
Hey there -

This is an amazing contribution - it was exactly what I was looking for, and I've already used it for multiple books! Thank you.

As a way to learn to code, I had actually started trying to build something similar using node.js before stumbling onto your extension. I'd still like to proceed with my project, but I'm having trouble getting the sfpl website to return the same page that you're able to get via background.js. (Right now, I get what looks like an error page, as it lists out a bunch of different errors - Recommendation Limit Reached, Excessive Checkout Limit Reached, An unexpected error has occurred, etc.)

Do you have any tips on how I could make sure my GET request is returning the same thing? Using the proper user-agent, I've been able to avoid the web-bot block, but haven't been able to move past this part yet.

`'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586'`

Thanks!

**Comment by rhollister** [comment]
You're welcome! It's an extension I had been wanting to do for myself for years, and I finally sat down and just wrote it in two nights (of course, adding many of the features has taken much more time than that!). 

I wonder if they're throttling you? As you noted, I'm making the request from background.js so I've never had to spoof anything- the request is literally the same as the browser visiting the page.

Have you tried comparing your request headers to what's being sent in a normal session?
