### ISSUE TITLE
Issue with one of my Libraries

### ISSUE THREAD

**Issue by mistborn-ops** [rhollister/goodreads#8]
https://fortbend.overdrive.com/ is the only library I have problems with.  It shows a bunch of books other than the one that I'm actually looking for.  I have attached a couple of screenshots that should help you see what I'm talking about.  It looks like they are using the new overdrive.  Also the extension did not like fortbend.overdrive.com I had to add it as fortbend.lib.overdrive.com and check the "Uses New overdrive site" option.

![screenshot 2016-06-19 11 41 47](https://cloud.githubusercontent.com/assets/8235167/16178615/13cea6a0-3613-11e6-961f-0c06fa91e651.png)
![screenshot 2016-06-19 11 42 18](https://cloud.githubusercontent.com/assets/8235167/16178616/13d21ac4-3613-11e6-8ed1-8d2ed222ab79.png)

**Comment by rhollister** [comment]
Looks like there was an issue in automatically checking for the new URL. I published a new update to 3.1.1. Chrome should auto-update it in the next day or so. Let me know if that fixes it!

**Comment by mistborn-ops** [comment]
I'm not sure if it's the same issue. However there have been several books that I've come across for the same library that is showing up as "Not Found" for the fortbend.overdrive.com.  I tried to find all of them but was only able to find a few of them.

in the attached screenshot, the underlined ones are books that I've found that are showing up as not found.

![screenshot 2016-07-14 07 47 39](https://cloud.githubusercontent.com/assets/8235167/16840056/3d5fabb6-4998-11e6-869d-8ec1796ac2e7.png)

**Comment by mistborn-ops** [comment]
Also in the attachment there is a typo in the mouseover for the Fortbend overdrive.  When it finds one it has "by" twice.

**Comment by rhollister** [comment]
I found the problem! That particular book was an Always Available copy which I wasn't checking in the Overdrive site design. It should be working now in version 3.2.0 of the extension.

Thanks for finding this bug!

**Comment by rhollister** [comment]
Oops, also fixed the "by" being in there twice. That'll be in 3.2.1.
