### ISSUE TITLE
Non-issue - This is awesome!

### ISSUE THREAD

**Issue by kevin789900** [rhollister/goodreads#9]
Thank you!  Sorry I didn't know where else to say thanks!  

How do you get access to multiple Overdrive libraries?  All libraries around me require you to live in city/township to get a card (or you have to pay fee to get card).

**Comment by rhollister** [comment]
You're welcome!

Fortunately most libraries in my area have reciprocal agreements with neighboring counties. In fact, my library has agreements with over 10 other library systems in the area. Which makes it really handy for finding an available book!

**Comment by taylorkline** [comment]
👍  I am loving this. Thank you!

What drives you to do this? Are you accepting donations?
